### PR TITLE
Story/quad77

### PR DESCRIPTION
**Pull request by rmanojcit**

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
well, now it's not getting fullscreen anymore:
image

**Comment by jdamerow** [comment]
retest this please

**Comment by rmanojcit** [comment]
I tried in firefox and chrome it works when i do it from normal screen.When i have inspect element open and do a full screen it doesn't appear full screen though

**Comment by jdamerow** [comment]
@rmanojcit, I fixed it for the public websites. What was happening was that the clear function was called even when going into fullscreen. I just made the div and svg to 100% all the time and removed all resizing. Please test if it still works on Windows and if so adjust the other two network pages. Thanks!

**Comment by jdamerow** [comment]
ps: if you just click on my last commit, you should see the files I changed:
https://github.com/diging/quadriga/pull/219/commits/3a4b4a5e3be92fb5bde81427863ac2376b4ab163

**Pull request closed without merging**
