### PR TITLE
Story/quad 51

### PR DESCRIPTION
**Pull request by suprajkolluri**

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
can we make disabled buttons look more disabled (more greyed out than they are right now)?
image

**Comment by suprajkolluri** [comment]
Please let me know if this color is good ?
screen shot 2016-01-27 at 10 11 02 am

**Comment by jdamerow** [comment]
retest this please

**Pull request merged**
