### PR TITLE
Fix invalid tags in PublicWebsiteEditAbout PAge

### PR DESCRIPTION
**Pull request by nischalsamji**
Fixed improper tag on develop branch.

### CODE REVIEW

**Comment by jdamerow** [comment]
@nischalsamji what bug does this fix?

**Comment by nischalsamji** [comment]
Some mis-alignment in the page as there was a misplaced UI tag in the page.

**Comment by jdamerow** [comment]
ok, please create a jira ticket next time please.

**Comment by jdamerow** [comment]
and use the ticket numbers as branch names. otherwise it creates chaos eventually :)

**Pull request closed without merging**
