### PR TITLE
story/QUAD-137 

### PR DESCRIPTION
**Pull request by PawanMahalle**
Consolidated stories QUAD-110, QUAD-112, QUAD-113 along with QUAD-137.

Previous [pull request](https://github.com/diging/quadriga/pull/197) containing unnecessary files has been closed.

Please review.

### CODE REVIEW

**Comment by jdamerow** [comment]
please resolve conflicts

**Comment by PawanMahalle** [comment]
Resolved conflicts. Please review.

**Comment by jdamerow** [comment]
Is this the same code as in 156? If so, let's close this PR and delete the branch and make all changes on 156.

**Comment by PawanMahalle** [comment]
The changes in this PR has been merged with other [pull request](https://github.com/diging/quadriga/pull/222) as instructed.

**Pull request closed without merging**
